// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVLS2dZ0S4PcguA9W0C5Va46hjjOyY6XM',
    appId: '1:90527969590:web:648b7ee2829b0e699bc397',
    messagingSenderId: '90527969590',
    projectId: 'market-flutter-f72fc',
    authDomain: 'market-flutter-f72fc.firebaseapp.com',
    databaseURL: 'https://market-flutter-f72fc-default-rtdb.firebaseio.com',
    storageBucket: 'market-flutter-f72fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACdvdeH-L4HrBDW4Da_8oe7EeI7Yegc-Q',
    appId: '1:90527969590:android:010b8e839cba68519bc397',
    messagingSenderId: '90527969590',
    projectId: 'market-flutter-f72fc',
    databaseURL: 'https://market-flutter-f72fc-default-rtdb.firebaseio.com',
    storageBucket: 'market-flutter-f72fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIva7seQAv6sleKRpsN2OVrD-Bj9sO9nI',
    appId: '1:90527969590:ios:19c338048b08075a9bc397',
    messagingSenderId: '90527969590',
    projectId: 'market-flutter-f72fc',
    databaseURL: 'https://market-flutter-f72fc-default-rtdb.firebaseio.com',
    storageBucket: 'market-flutter-f72fc.appspot.com',
    iosClientId: '90527969590-665fdskh1lqsplf2h24fnfm58j3s8ah7.apps.googleusercontent.com',
    iosBundleId: 'com.example.market',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIva7seQAv6sleKRpsN2OVrD-Bj9sO9nI',
    appId: '1:90527969590:ios:19c338048b08075a9bc397',
    messagingSenderId: '90527969590',
    projectId: 'market-flutter-f72fc',
    databaseURL: 'https://market-flutter-f72fc-default-rtdb.firebaseio.com',
    storageBucket: 'market-flutter-f72fc.appspot.com',
    iosClientId: '90527969590-665fdskh1lqsplf2h24fnfm58j3s8ah7.apps.googleusercontent.com',
    iosBundleId: 'com.example.market',
  );
}
